syntax = "proto3";

package proto;

import "google/protobuf/timestamp.proto";

option go_package = "spectral-assignment/gen/proto";

message SensorReading {
  google.protobuf.Timestamp timestamp = 1;
  double value = 2;
}

message GetPageRequest {
  google.protobuf.Timestamp cursor = 1;
  int32 limit = 2;
}

message GetPageResponse {
  optional google.protobuf.Timestamp next_cursor = 1;
  repeated SensorReading data = 2;
}

service SensorService {
  rpc GetPage(GetPageRequest) returns (GetPageResponse);
}
