syntax = "proto3";

package proto.v1;

option go_package = "spectral-assignment/gen/proto/v1;protov1";

message SensorData {
  int64 timestamp = 1;
  double value = 2;
}

message GetPageRequest {
  int64 cursor = 1;
  int32 limit = 2;
}

message GetPageResponse {
  optional int64 next_cursor = 1;
  repeated SensorData data = 2;
}

message GetCountRequest {}

message GetCountResponse {
  uint64 count = 1;
}

service SensorService {
  rpc GetPage(GetPageRequest) returns (GetPageResponse);
  rpc GetCount(GetCountRequest) returns (GetCountResponse);
}
